# Generated by Django 5.1.5 on 2025-01-19 17:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0003_room_alter_chatuser_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='chatuser',
            name='email',
            field=models.EmailField(default=None, max_length=254),
        ),
    ]
